version: '3.8'
services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=btXaqCnLKREde3I8QOGtCwEGezWxBTa6pP1N7IgW/Lk=   # openssl rand -hex 32
    ports:
      - 3000:3000
    
  db:
    container_name: db
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    profiles:
      - donotstart